# Generated by Django 4.1.4 on 2022-12-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='recoverd',
            field=models.IntegerField(default=0),
        ),
    ]
