# Generated by Django 4.1.4 on 2022-12-17 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covidtask', '0002_country_recoverd'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='subscription',
            field=models.ManyToManyField(db_table='Subscription', related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='confirmed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='death',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='recoverd',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
